
  CREATE TABLE "PBBDUMMY"."LOG_REVERSAL"
   (	"NOP" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"THN" VARCHAR2(4 BYTE) NOT NULL ENABLE,
	"NTPD" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"IP_CLIENT" VARCHAR2(30 BYTE),
	 CONSTRAINT "LOG_REVERSAL_PK" PRIMARY KEY ("NOP", "THN", "NTPD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT" ;
